[package]
edition = "2021"
name = "rnr"
version = "0.1.0"
[dependencies]
indented = "0.1.0"
proc-macro2 = "1.0.69"
quote = "1.0.33"
regex = "1.10.2"
structopt = "0.3.26"

[dependencies.syn]
features = ["full", "extra-traits"]
version = "2.0.39"
